name: spotify_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.17.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/vectors/
    - assets/images/
    - assets/audio/

  fonts:
    - family: TiktokSans  
      fonts:
        - asset: assets/fonts/TiktokSans-Black.ttf
        - asset: assets/fonts/TiktokSans-Bold.ttf
        - asset: assets/fonts/TiktokSans-Light.ttf
        - asset: assets/fonts/TiktokSans-Medium.ttf
        - asset: assets/fonts/TiktokSans-Regular.ttf
        - asset: assets/fonts/TiktokSans-SemiBold.ttf
