// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-k71pRTZdgRCE6qXlqhy9DUq0Mz1TfQ0',
    appId: '1:3775908691:web:4931f9913cdad3ddc4efa6',
    messagingSenderId: '3775908691',
    projectId: 'spotify-e8642',
    authDomain: 'spotify-e8642.firebaseapp.com',
    storageBucket: 'spotify-e8642.firebasestorage.app',
    measurementId: 'G-M6XQREEEG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsPs5cg6rTV_LrdSCbGUzrjIuqYyKMJVM',
    appId: '1:3775908691:android:01c48696e08f1d17c4efa6',
    messagingSenderId: '3775908691',
    projectId: 'spotify-e8642',
    storageBucket: 'spotify-e8642.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJcDDX4k1wUSTs9BsWAVmSC2brNqHVHf8',
    appId: '1:3775908691:ios:f8d174e13e53cd8fc4efa6',
    messagingSenderId: '3775908691',
    projectId: 'spotify-e8642',
    storageBucket: 'spotify-e8642.firebasestorage.app',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJcDDX4k1wUSTs9BsWAVmSC2brNqHVHf8',
    appId: '1:3775908691:ios:f8d174e13e53cd8fc4efa6',
    messagingSenderId: '3775908691',
    projectId: 'spotify-e8642',
    storageBucket: 'spotify-e8642.firebasestorage.app',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-k71pRTZdgRCE6qXlqhy9DUq0Mz1TfQ0',
    appId: '1:3775908691:web:907586a040bae327c4efa6',
    messagingSenderId: '3775908691',
    projectId: 'spotify-e8642',
    authDomain: 'spotify-e8642.firebaseapp.com',
    storageBucket: 'spotify-e8642.firebasestorage.app',
    measurementId: 'G-50DRH94B16',
  );
}
